### ISSUE TITLE
Calculation Issue

### ISSUE THREAD

**Issue by mikagrubinen** [polymurph/MAX31865#2]
https://github.com/polymurph/MAX31865/blob/d9077ca31ac6685d21dc90538f7de2b2a9d7e449/max31865.c#L145

I think this is not the correct way of grabbing the results. You right-shifted LSB for 1 bit, and left-shifted MSB for 8 bits. So one bit is "inserted" between MSB and LSB. I think MSB should only be left-shifter for 7 bits.

Something like this:
uint16_t msb = (uint16_t)buff[0] << 7;
uint16_t lsb = (uint16_t)buff[1] >> 1;
result = msb | lsb;

BTW, thank you for the code.

**Comment by polymurph** [comment]
@mikagrubinen You are correct. I changed the cited line of code to the following; " return (uint16_t)buff[0] << 7 | (uint16_t)buff[1] >> 1; "
Has that solved your problem? Let me know. 

With pleasure. More such code should be on it's way soon... hopefully. Also thank you for your help!

P.S. May I ask; for what project are you using this code?

**Comment by mikagrubinen** [comment]
I didn't end up using the code since we are using somewhat weird SPI implementation. But it served me as a good starting point to understand the chip. I was lazy to read the datasheet ::-D
